import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mridul Ganga
 */
public class DuesForm extends javax.swing.JFrame {

    /**
     * Creates new form DuesForm
     */
    public DuesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        chk_P = new javax.swing.JRadioButton();
        chk_GP = new javax.swing.JRadioButton();
        T_Name = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        T_Amount = new javax.swing.JTextField();
        BTNEntry = new javax.swing.JButton();
        BTNPaid = new javax.swing.JButton();
        BTNRecieved = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("To Pay");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Will be Paid");

        jLabel3.setText("New Entry:");

        buttonGroup1.add(chk_P);
        chk_P.setText("Pay");

        buttonGroup1.add(chk_GP);
        chk_GP.setText("Get Paid");

        T_Name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("by or to");

        jLabel5.setText("Amount");

        BTNEntry.setText("Add Entry");
        BTNEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEntryActionPerformed(evt);
            }
        });

        BTNPaid.setText("Paid");
        BTNPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPaidActionPerformed(evt);
            }
        });

        BTNRecieved.setText("Received");
        BTNRecieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRecievedActionPerformed(evt);
            }
        });

        T2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(T2);

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(T1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel1)
                                        .addGap(156, 156, 156))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNPaid)
                                        .addGap(142, 142, 142)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNRecieved)))))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(chk_P)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_GP)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNEntry)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BTNPaid)
                                .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNRecieved)
                            .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chk_P)
                    .addComponent(chk_GP)
                    .addComponent(T_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(T_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEntry))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEntryActionPerformed
        
        String payee,tpay;
        if (chk_P.isSelected())
        {
             tpay = T_Name.getSelectedItem().toString();
             payee = DBC.currentUser;
        }
        else
        {
             tpay = DBC.currentUser;
             payee = T_Name.getSelectedItem().toString();
        }
        String amount = ""+(Integer.parseInt(T_Amount.getText()) + previousDue(payee,tpay));
        
        String id = (getMaxID()+1)+"";
        String sql = "insert into dues values("+id+",'"+payee+"','"+tpay+"',"+amount+")";
        
        Connection con = DBC.ConnectDB();
        DBC.ExecuteSQL(con, "delete from dues where payee='"+payee+"' and tpay='"+tpay+"'");
        DBC.ExecuteSQL(con, sql);
        loadDues();
        DBC.DisconnectDB(con);
    }//GEN-LAST:event_BTNEntryActionPerformed

    private int previousDue(String payee,String tpay)
    {
        Connection con = DBC.ConnectDB();
        try{
            ResultSet R = DBC.getTable(con, "Select amount from dues where tpay='"+tpay+"' and payee='"+payee+"'");
            R.first();
            int amount =R.getInt("amount");
            return amount;
        }catch(Exception e){return 0;}
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadNames();
        loadDues();
    }//GEN-LAST:event_formWindowOpened

    private void BTNPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPaidActionPerformed
            
            DefaultTableModel model = (DefaultTableModel) T1.getModel();
            String val = "" + model.getValueAt(T1.getSelectedRow(), 0);
            int due=previousDue(DBC.currentUser,val)-Integer.parseInt(TF1.getText());
            
            Connection con = DBC.ConnectDB();
            if (due==0)
            {
                DBC.ExecuteSQL(con, "Delete from dues where payee='" + DBC.currentUser + "' and tpay='"+val+"'");
            }
            else
            {
                DBC.ExecuteSQL(con, "update dues set amount = " + due +" where payee='" + DBC.currentUser + "' and tpay='"+val+"'");
            }
            
            
            DBC.DisconnectDB(con);
            loadDues();

    }//GEN-LAST:event_BTNPaidActionPerformed

    private void BTNRecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRecievedActionPerformed
            DefaultTableModel model = (DefaultTableModel) T2.getModel();
            String val = "" + model.getValueAt(T2.getSelectedRow(), 0);
            int due=previousDue(val,DBC.currentUser)-Integer.parseInt(TF2.getText());
            
            Connection con = DBC.ConnectDB();
            if (due==0)
            {
                DBC.ExecuteSQL(con, "Delete from dues where tpay='" + DBC.currentUser + "' and payee='"+val+"'");
            }
            else
            {
                DBC.ExecuteSQL(con, "update dues set amount = " + due +" where tpay='" + DBC.currentUser + "' and payee='"+val+"'");
            }
            
            
            DBC.DisconnectDB(con);
            loadDues();
    }//GEN-LAST:event_BTNRecievedActionPerformed

    private void loadNames()
    {
              int i=0;
        Connection con = DBC.ConnectDB();
       ResultSet R = DBC.getTable(con, "select Count(*)'count' from members");
       try{
           R.first();
           int count=R.getInt("count");
           R.close();
           
           R = DBC.getTable(con,"select * from members");
           String[] mNames = new String [count];
           while(R.next())
           {
               mNames[i]=R.getString("name");
               i++;
           }
           T_Name.setModel(new javax.swing.DefaultComboBoxModel(mNames));
       }catch(Exception e)
       {
           System.out.println(e);
       }
       DBC.DisconnectDB(con);
       
    }
    
    private void loadDues()
    {
        String payee,amount;
        DefaultTableModel model1 = (DefaultTableModel) T1.getModel();
        model1.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel) T2.getModel();
        model2.setRowCount(0);
        
     //  To Pay
        Connection con = DBC.ConnectDB();
        try{
            
        ResultSet R1 = DBC.getTable(con, "select tpay,amount from dues where payee='"+DBC.currentUser+"'");
        while (R1.next())
        {
            payee = R1.getString("tpay");
            amount = R1.getString("amount");
            model1.addRow(new Object[]{payee,amount});
                T1.setModel(model1);
        }
     // To be Paid From
        ResultSet R2 = DBC.getTable(con, "select payee,amount from dues where tpay='"+DBC.currentUser+"'");
        while (R2.next())
        {
            payee = R2.getString("payee");
            amount = R2.getString("amount");
            model2.addRow(new Object[]{payee,amount});
                T2.setModel(model2);
        }
        }catch(Exception e){}
    } // End of LoadDues Method
    
        private int getMaxID()
{
     int maxID=0;
    Connection con = DBC.ConnectDB();
    ResultSet R = DBC.getTable(con, "Select max(id)'id' from dues");
        
    try {
        R.first();
            maxID=R.getInt("id");
            return maxID;
        } catch (Exception e) {
            System.out.println(e);
        }
    
        DBC.DisconnectDB(con);
        return 0;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DuesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DuesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DuesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEntry;
    private javax.swing.JButton BTNPaid;
    private javax.swing.JButton BTNRecieved;
    private javax.swing.JTable T1;
    private javax.swing.JTable T2;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField T_Amount;
    private javax.swing.JComboBox T_Name;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chk_GP;
    private javax.swing.JRadioButton chk_P;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
