
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mridul Ganga
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_Trans = new javax.swing.JTable();
        BTNNewEntry = new javax.swing.JButton();
        BTNDelete = new javax.swing.JButton();
        BTNDues = new javax.swing.JButton();
        BTNMembers = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BTNLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        T_Trans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sl. No.", "Remark", "Date", "Shared By", "ATM Withdrawl", "Spending"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(T_Trans);

        BTNNewEntry.setText("Add Entry");
        BTNNewEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNewEntryActionPerformed(evt);
            }
        });

        BTNDelete.setText("Remove Entry");
        BTNDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteActionPerformed(evt);
            }
        });

        BTNDues.setText("Dues");
        BTNDues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDuesActionPerformed(evt);
            }
        });

        BTNMembers.setText("Members");
        BTNMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMembersActionPerformed(evt);
            }
        });

        jButton1.setText("Net Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTNLogout.setText("Logout");
        BTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BTNNewEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNDelete)
                .addGap(36, 36, 36)
                .addComponent(BTNDues)
                .addGap(18, 18, 18)
                .addComponent(BTNMembers)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNLogout)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNNewEntry)
                    .addComponent(BTNDelete)
                    .addComponent(BTNDues)
                    .addComponent(BTNMembers)
                    .addComponent(jButton1)
                    .addComponent(BTNLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNNewEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNewEntryActionPerformed
        new NewEntryForm().setVisible(true);
    }//GEN-LAST:event_BTNNewEntryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadTrans();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadTrans();
    }//GEN-LAST:event_formWindowGainedFocus

    private void BTNDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteActionPerformed
int res = JOptionPane.showConfirmDialog(null, "Sure you wish to delete this Transaction?");
        if (res==0)
        {
            DefaultTableModel model = (DefaultTableModel) T_Trans.getModel();
            String val = "" + model.getValueAt(T_Trans.getSelectedRow(), 0);
            Connection con = DBC.ConnectDB();
            DBC.ExecuteSQL(con, "Delete from transaction where id=" + val);
            DBC.DisconnectDB(con);
            loadTrans();
        }
    }//GEN-LAST:event_BTNDeleteActionPerformed

    private void BTNDuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDuesActionPerformed
        new DuesForm().setVisible(true);
    }//GEN-LAST:event_BTNDuesActionPerformed

    private void BTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogoutActionPerformed

        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_BTNLogoutActionPerformed

    private void BTNMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMembersActionPerformed
        new MembersForm().setVisible(true);
    }//GEN-LAST:event_BTNMembersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new NetTransForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    loadTrans();
    }//GEN-LAST:event_formWindowActivated

    
    private void loadTrans()
    {
        Connection con = DBC.ConnectDB();
        ResultSet R = DBC.getTable(con, "select * from transaction where name ='" + DBC.currentUser+"'");

        DefaultTableModel model = (DefaultTableModel) T_Trans.getModel();
        model.setRowCount(0);
        int W,S;
        try {
            while (R.next()) {
                int id = R.getInt("id");
                String remark = R.getString("remark");
              int ttype = R.getInt("ttype");
                String date = "" + R.getDate("date");
                String sharedby= R.getString("shared");
              int amount = R.getInt("amount");
              if (ttype==1)
              {  W = amount; S=0;}
              else
              { W=0; S=amount;}
              
                
                model.addRow(new Object[]{id, remark, date, sharedby, W, S});
                T_Trans.setModel(model);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        DBC.DisconnectDB(con);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                        DBC.firstRun();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDelete;
    private javax.swing.JButton BTNDues;
    private javax.swing.JButton BTNLogout;
    private javax.swing.JButton BTNMembers;
    private javax.swing.JButton BTNNewEntry;
    private javax.swing.JTable T_Trans;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
