
import java.sql.Connection;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mridul Ganga
 */
public class NewEntryForm extends javax.swing.JFrame {

    /**
     * Creates new form NewEntryForm
     */
    public NewEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        T_Remark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T_SharedBy = new javax.swing.JTextField();
        T_Amount = new javax.swing.JTextField();
        BTNEntry = new javax.swing.JButton();
        BTNCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        T_Date = new javax.swing.JTextField();
        T_PaidBy = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        chk_W = new javax.swing.JRadioButton();
        chk_S = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Paid By");

        jLabel2.setText("Remark");

        jLabel3.setText("Shared By");

        jLabel4.setText("Amount");

        BTNEntry.setText("Add Entry");
        BTNEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEntryActionPerformed(evt);
            }
        });

        BTNCancel.setText("Cancel");
        BTNCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelActionPerformed(evt);
            }
        });

        jLabel5.setText("Date");

        T_PaidBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));

        jLabel6.setText("Type of Transaction");

        buttonGroup1.add(chk_W);
        chk_W.setText("ATM Withdrawl");

        buttonGroup1.add(chk_S);
        chk_S.setSelected(true);
        chk_S.setText("Spending");

        jLabel7.setText("YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(chk_W)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_S))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNEntry)
                                .addGap(18, 18, 18)
                                .addComponent(BTNCancel))
                            .addComponent(T_SharedBy)
                            .addComponent(T_Remark)
                            .addComponent(T_Amount)
                            .addComponent(T_Date)
                            .addComponent(T_PaidBy, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(T_PaidBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T_Remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(T_SharedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chk_W)
                    .addComponent(chk_S))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNEntry)
                    .addComponent(BTNCancel))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       int i=0;
        Connection con = DBC.ConnectDB();
       ResultSet R = DBC.getTable(con, "select Count(*)'count' from members");
       try{
           R.first();
           int count=R.getInt("count");
           R.close();
           
           R = DBC.getTable(con,"select * from members");
           String[] mNames = new String [count];
           while(R.next())
           {
               mNames[i]=R.getString("name");
               i++;
           }
           T_PaidBy.setModel(new javax.swing.DefaultComboBoxModel(mNames));
       }catch(Exception e)
       {
           System.out.println(e);
       }
       DBC.DisconnectDB(con);
       
       T_PaidBy.setSelectedItem(DBC.currentUser);
    }//GEN-LAST:event_formWindowOpened

    private void BTNEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEntryActionPerformed
        Connection con = DBC.ConnectDB();
        String ttype;
        if (chk_W.isSelected())
            ttype="1";
        else
            ttype="0";
        //Check for date validity Here
        String sql="insert into transaction values("+String.valueOf(getMaxID()+1)+",'"+T_PaidBy.getSelectedItem().toString();
        sql=sql+"'," + ttype+",'"+T_Remark.getText()+"','"+T_Date.getText()+"',"+T_Amount.getText()+",'"+T_SharedBy.getText()+"')";
        System.out.println(sql);
        DBC.ExecuteSQL(con, sql);
        this.dispose();
    }//GEN-LAST:event_BTNEntryActionPerformed

    private void BTNCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelActionPerformed

    
    private int getMaxID()
{
     int maxID=0;
    Connection con = DBC.ConnectDB();
    ResultSet R = DBC.getTable(con, "Select max(id)'id' from transaction");
        
    try {
        R.first();
            maxID=R.getInt("id");
            return maxID;
        } catch (Exception e) {
            System.out.println(e);
        }
    
        DBC.DisconnectDB(con);
        return 0;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEntryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancel;
    private javax.swing.JButton BTNEntry;
    private javax.swing.JTextField T_Amount;
    private javax.swing.JTextField T_Date;
    private javax.swing.JComboBox T_PaidBy;
    private javax.swing.JTextField T_Remark;
    private javax.swing.JTextField T_SharedBy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chk_S;
    private javax.swing.JRadioButton chk_W;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
